[package]
name = "things"
version = "0.1.0"
edition = "2021"


[dependencies]
# clap = { version = "4.0", features = ["derive"] }
inquire = { version = "0.6.2", features = ["date"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
